#!/usr/bin/env bash
# Your machine has an SSH configuration file for the local SSH client

SendEnv LANG LC_*
HashKnownHosts yes
GSSAPIAuthentication yes
PasswordAuthentication no
IdentityFile ~/.ssh/school